services:
  db:
    image: mysql:8.0
    container_name: bankdb
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/database:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: bankdb
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SERVICE_TAGS: prod
      SERVICE_NAME: db
    networks:
      - internalnet

  api:
    container_name: bank-backend
    build: .
    image: bank-backend
    environment:
      DB_HOST: bankdb
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: bankdb
      DB_PORT: 3306
      DB_CONNECTION_LIMIT: 10
      SERVER_PORT: 3000
      SERVICE_TAGS: prod
      SERVICE_NAME: api
    ports:
      - "3000:3000"
    expose:
        - "3000"
    depends_on:
      - db
    networks:
        - internalnet





networks:
  internalnet:
    driver: bridge
